baseURL = "https://amree.dev"
languageCode = "en-us"
title = "Amree Zaid"
theme = "terminal"

[pagination]
  pagerSize = 5

[params]
  contentTypeName = "posts"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true

  subtitle = "A place for me to share something"
  menuMore = "Show more"
  readMore = "Read more"
  readOtherPosts = "Read other posts"
  newerPosts = "Newer posts"
  olderPosts = "Older posts"
  missingContentMessage = "Page not found..."
  missingBackButtonLabel = "Back to home page"

  [params.logo]
    logoText = "Amree Zaid"
    logoHomeLink = "/"

  [params.twitter]
    creator = "AmreeZaid"
    site = "AmreeZaid"

[taxonomies]
  tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
  posts = "/:year/:month/:day/:title/"

[menu]
  [[menu.main]]
    identifier = "archive"
    name = "Archive"
    url = "/archive"
    weight = 1

  [[menu.main]]
    identifier = "random"
    name = "Random"
    url = "/random"
    weight = 2

  [[menu.main]]
    identifier = "x"
    name = "X"
    url = "https://x.com/AmreeZaid"
    weight = 3

  [[menu.main]]
    identifier = "github"
    name = "Github"
    url = "https://github.com/amree"
    weight = 4
